# Generated by Django 2.2.3 on 2019-07-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (0, 'Female')], default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(default='0000'),
        ),
    ]
