# Generated by Django 2.2.3 on 2019-07-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20190729_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(default='0000', max_length=20),
        ),
    ]
